drop schema  PROGWEB_RAPHAEL;

create database PROGWEB_RAPHAEL;

use PROGWEB_RAPHAEL;

CREATE TABLE COMENTARIO(
ID INT NOT NULL AUTO_INCREMENT,
NOME VARCHAR(50) NOT NULL,
SEXO INT,
MENSAGEM VARCHAR(140),
PRIMARY KEY (ID)
);

SELECT * FROM COMENTARIO;